[package]
name = "minikui_notifications"
version = "0.1.0"
edition = "2021"
description = "Scripts for handling notifications."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
